# Generated by Django 6.1.1 on 2026-09-17 12:15

import trainings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attendance_code',
            field=models.CharField(default=trainings.models.generate_attendance_code, max_length=4),
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('법정 필수', '법정 필수'), ('사내 교육', '사내 교육'), ('기타', '기타')], default='사내 교육', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
